name: Build Bicep to ARM and push to publish branch

run-name: Build Bicep to ARM and push to publish branch
on:
  push:
    branches:
      - dev
      - master
    paths:
      - MDELab/modules/*.bicep
      - MDILab/modules/*.bicep
      - OceanLotus/modules/*.bicep
      - Linux/modules/*.bicep
      - Common/DSC/*.ps1
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'The branch to run the workflow against'
        required: true
        default: published

permissions:
  contents: write

concurrency:
  group: bicep-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Labs
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Bicep and build templates
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Installing Bicep"
            az bicep install
            az bicep upgrade

      - name: Build Bicep to ARM JSON
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Az Version"
            az version

            echo "bicep version"
            az bicep version

            find . -type f -name '*.bicep' ! -path '*/Common/*' | while read file; do
              firstdir="${file#./}"
              firstdir="${firstdir%%/*}"

              out="./tmp/$firstdir"
              echo "Building $file to $out"
              
              az bicep build --file "$file" --outdir "$out"
            done

      - name: Copy Supporting Files
        run: |
         mkdir -p DSC
         rsync -a Common/DSC/ DSC/

      - name: Switch to target branch and stage artifacts
        id: prepare
        run: |
          TARGET_BRANCH="${{ github.event.inputs.target-branch }}"
          CURRENT_BRANCH="${{ github.ref_name }}"
          if [ $CURRENT_BRANCH == "master" ]; then
            CURRENT_BRANCH="pub"
          fi
          echo "Switching to branch $TARGET_BRANCH. Current Branch folder is $CURRENT_BRANCH"

          #fetch and checkout branch
          git fetch origin $TARGET_BRANCH || true
          if git rev-parse --verify origin/$TARGET_BRANCH; then
            git checkout $TARGET_BRANCH
            git pull
          else
            git checkout -b $TARGET_BRANCH
          fi

          rsync -a --delete tmp/ $CURRENT_BRANCH/
          rsync -a --delete DSC $CURRENT_BRANCH/

          git add $CURRENT_BRANCH

      - name: Commit and push to publish branch
        run: | 
          TARGET_BRANCH="${{ github.event.inputs.target-branch }}"
          

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit -m "Bicep build artifacts for commit $GITHUB_SHA" || echo "No changes to commit"
          git push origin HEAD:$TARGET_BRANCH