name: Build Bicep to ARM and push to publish branch

run-name: Test bicep build
on:
  push:
    branches:
      - actions
    paths:
      - MDELab/modules/*.bicep
      - MDILab/modules/*.bicep
      - OceanLotus/modules/*.bicep
  workflow_dispatch:
    inputs:
      target-branch:
        description: 'The branch to run the workflow against'
        required: true
        default: published

permissions:
  contents: write

concurrency:
  group: bicep-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Labs
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Bicep and build templates
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Installing Bicep"
            az bicep install
            az bicep upgrade

      - name: Build Bicep to ARM JSON
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            echo "Az Version"
            az version

            echo "bicep version"
            az bicep version

            find . -type f -name '*.bicep' ! -path '*/Common/*' | while read file; do
              firstdir="${file#./}"
              firstdir="${firstdir%%/*}"

              out="./pub/$firstdir"
              echo "Building $file to $out"
              
              az bicep build --file "$file" --outdir "$out"
            done

      - name: Switch to target branch and stage artifacts
        id: prepare
        run: |
          TARGET_BRANCH="${{ github.event.inputs.target-branch }}"
          echo "Switching to branch $TARGET_BRANCH"

          #fetch and checkout branch
          git fetch origin $TARGET_BRANCH || true
          if git rev-parse --verify origin/$TARGET_BRANCH; then
            git checkout $TARGET_BRANCH
            git pull
          else
            git checkout -b $TARGET_BRANCH
          fi

          cd pub

          find . -type f | while read file; do
            echo "Adding $file to publication branch"
            git add "$file"
          done

          cd ..

      - name: Copy supporting files
        run: |
          TARGET_BRANCH="${{ github.event.inputs.target-branch }}"
          echo "Copying supporting files to branch $TARGET_BRANCH"

          mkdir -p pub/DSC
          cp ./Common/DSC/* pub/DSC

          git add pub/DSC

      
      - name: Commit and push to publish branch
        run: | 
          TARGET_BRANCH="${{ github.event.inputs.target-branch }}"
          echo "Committing and pushing to branch $TARGET_BRANCH"

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git commit -m "Bicep build artifacts for commit $GITHUB_SHA" || echo "No changes to commit"
          git push origin HEAD:$TARGET_BRANCH